name: CICD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.11'
      - name: Build
        run: mkdir build && go build -o build/saml-simulator cmd/saml-simulator/*
      - name: Test
        env:
          CGO_ENABLED=0
        run: go test ./...

