name: CICD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64]
        include:
          - os: linux
            ext: ""
          - os: darwin
            ext: .app
          - os: windows
            ext: .exe
    env:
      CGO_ENABLED: 0
      GOOS: ${{ matrix.os }}
      GOARCH: ${{ matrix.arch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.11'
      - name: Build
        run: mkdir -p build && go build -o build/saml-simulator${{ matrix.ext }} cmd/saml-simulator/*
      - name: Test
        run: go test ./...
  docker:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.11'
      - name: Build
        run: mkdir -p build && go build -o build/saml-simulator cmd/saml-simulator/*
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
