name: Release
on:
  release:
    types:
      - published
jobs:
  docker_push:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.11'
      - name: Build
        run: mkdir -p build && go build -o build/saml-simulator cmd/saml-simulator/*
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: tekkamanendless/saml-simulator:${{ github.event.release.tag_name }}
